---
- name: install the latest version of Docker
  apt: name=docker state=latest update_cache=yes

- name: install python-pip
  apt: name=python-pip state=latest

#- name: install docker-machine
#  yum: name=docker-machine state=present

- name: install apt-transport-https
  apt: name=apt-transport-https state=latest

- name: install ca-certificates
  apt: name=ca-certificates state=latest

- apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list owner=root group=root mode=0644

- name: install docker-engine
  apt: name=docker-engine state=present update_cache=yes


- name: install docker-py
  pip: name=docker-py state=present

- name: start Docker service
  service: name=docker state=started

- name: Add vagrant to group docker
  user: name=vagrant groups=docker append=yes
